apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-pv-manual
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/dados-residuos" # O caminho real na sua VM Oracle