apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: processamento-residuos
  namespace: default
spec:
  type: Python
  mode: cluster
  image: "apache/spark:3.4.1"
  pythonVersion: "3"
  mainApplicationFile: "local:///dados/scripts/processamento.py"
  sparkVersion: "3.4.1"
  driver:
    cores: 1
    memory: "512m"
    serviceAccount: cracha-gerenciador-pods
    labels:
      version: 3.4.1
    volumeMounts:
      - name: dados-volume
        mountPath: /dados
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    serviceAccount: cracha-gerenciador-pods
    labels:
      version: 3.4.1
    volumeMounts:
      - name: dados-volume
        mountPath: /dados
  volumes:
    - name: dados-volume
      persistentVolumeClaim:
        claimName: spark-pvc